# Packages
#===========================================================
[packages]
host = "https://github.com/herlegon/rehost/releases/download/external"
do_cache = false


# Windows
#-----------------------------------------------------------
# [packages.win32]
# do_cache = false
[packages.win32.ffmpeg]
host = "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-26-13-03/"
do_cache = false

[packages.win32.ffmpeg.lgpl]
filename = "ffmpeg-n9.0.2-10-g51c4a23d74-win64-lgpl-9.0.zip"


# Linux
#-----------------------------------------------------------
[packages.linux.ffmpeg]
host = "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-09-26-13-03/"
do_cache = true

[packages.linux.ffmpeg.lgpl]
filename = "ffmpeg-n9.0.2-10-g51c4a23d74-linux64-lgpl-9.0.tar.xz"


# Python packages
#===========================================================

# Second pass
[py_packages.delayed]
do_cache = false

# PyTorch
[py_packages.delayed.torch.cuda]
index-url = "https://download.pytorch.org/whl/cu132"
torch = "2.14.0+cu132"
torchvision = "0.29.0+cu132"

[py_packages.delayed.torch.cpu]
index-url = "https://download.pytorch.org/whl/cpu"
torch = "2.14.0+cpu"
torchvision = "0.29.0+cpu"


# Pretty names
#===========================================================
[packages.names]
ffmpeg = "FFmpeg"

[py_packages.names]
nvidia-ml-py = "pyNVML"
torch = "PyTorch"
torch-cuda = "PyTorch (CUDA)"
torch-cpu = "PyTorch (CPU)"
torch-rocm = "PyTorch (ROCm)"
torchvision = "TorchVision"
